[package]
name = "core-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22"
rand.workspace = true
sha2.workspace = true
windows.workspace = true
hex = "0.4"
